// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce-lite",
  description: "Generated by create next app",
  authors: [
    { name: "Alvaro Ariza", url: "https://github.com/alvarojunior22" },
    { name: "juseth porto", url: "https://github.com/Jusethporto" },
    { name: "elias cardenas", url: "https://github.com/santiagolopezbarbosa" },
  ],
  publisher: "Ecommerce-lite",

  openGraph: {
    title: "Ecommerce-lite",
    description: "La tienda online moderna hecha con Next.js",
    url: "https://ecommerce-lite.com",
    siteName: "Ecommerce-lite",
    type: "website",
  }
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Navbar />
        </header>

        <main className="min-h-screen bg-gray-50">
          {children}
        </main>

        <footer>
         <Footer/>
        </footer>
      </body>
    </html>
  );
}
